app/controllers/itineraries_controller.rb
app/controllers/preferences_controller.rb
app/controllers/sessions_controller.rb
app/controllers/stops_controller.rb
app/models/category.rb
app/models/city.rb
app/models/itinerary.rb
app/models/sight.rb
app/models/user.rb
app/views/preferences/index.html.erb
app/views/stops/create.html.erb
app/views/stops/destroy.html.erb
app/views/stops/show.html.erb
config/routes.rb
test/controllers/stops_controller_test.rb

Model and controller improvements

---

app/controllers/preferences_controller.rb
app/views/preferences/categories.html.erb
app/views/preferences/cities.html.erb

pretty much same, but now cities and categories come from the actual db, and user can select more than one category (now it's for real, the one before was ahead of remote, now it's all good)

Cities search

---

app/controllers/preferences_controller.rb
app/views/preferences/result.html.erb

Filtered sights based on cities

filtered sights based on cities

---

Gemfile
Gemfile.lock
app/controllers/itineraries_controller.rb
app/controllers/sights_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/models/sight.rb
app/views/itineraries/show.html.erb
app/views/layouts/application.html.erb
config/application.rb
config/initializers/geocoder.rb

geocoding half done

---

app/controllers/itineraries_controller.rb
app/javascript/controllers/map_controller.js
app/views/itineraries/show.html.erb
app/views/layouts/application.html.erb

added optimized route on mapbox

---

app/controllers/preferences_controller.rb
app/controllers/sights_controller.rb
app/controllers/stops_controller.rb
app/views/preferences/categories.html.erb
app/views/sights/show.html.erb
app/views/stops/create.html.erb
config/routes.rb

With this PR we managed to finish the sorting logic for the sights. We also created initeraries and stops.

Sight sorting iti and stop creation

---

app/assets/stylesheets/components/_index.scss
config/environments/production.rb

last checks

---

app/assets/stylesheets/components/_categories.scss
app/views/preferences/categories.html.erb

everything works, let's see if it works for anusha too

trying to change alignment of categories, still no luck

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_checkbox.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/preferences_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/preferences_controller.js
app/views/preferences/categories.html.erb
app/views/shared/_navbar.html.erb

Some minor improvements on navbar. Back button doesnt move downwards anymore when profile button is opened, and profile button lost its dreadful border.

Navbar improvements

---

app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_checkbox.scss
app/controllers/preferences_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/preferences_controller.js
app/views/preferences/categories.html.erb

our categories look good! I used stimulus to mark in green the categories that are selected - and that persists until untapped. I also managed to remove the check thingy. finally, styled the ok button and improved spacing all around.

Categories alignment

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_cities.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/preferences_controller.rb
app/views/preferences/cities.html.erb

Cities form logic is ready, but styling needed

---

app/assets/stylesheets/components/_map.scss
app/controllers/itineraries_controller.rb
app/controllers/preferences_controller.rb
app/javascript/controllers/map_controller.js

img card in itenarery in progress

stop-img in progress

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_duration.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/preferences_controller.rb
app/views/preferences/duration.html.erb

duration page done

---

app/assets/stylesheets/components/_map.scss
app/controllers/preferences_controller.rb

navigation fixed - now the filter is working again. also did some minor display fixes on map and navbar

Nav duration bug fix

---

app/assets/stylesheets/components/_map.scss
app/controllers/preferences_controller.rb
app/views/shared/_navbar.html.erb

Now the mapbox logo is placed somewhere less obtrusive and the info mapbox icon is hidden

Map logo icon fix

---

app/controllers/preferences_controller.rb
app/controllers/stops_controller.rb
config/routes.rb

deleted itinerary with no stops

deleted itinerary

---

app/javascript/controllers/map_controller.js

mapfixed - no address - new seeds still in

---

db/seeds.rb

seed improved

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_cities.scss
app/assets/stylesheets/pages/_show.scss
app/views/preferences/categories.html.erb
app/views/preferences/duration.html.erb
app/views/sights/show.html.erb

styling fixes

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_itineraries-index.scss
app/controllers/itineraries_controller.rb
app/views/itineraries/index.html.erb
app/views/stops/index.html.erb

implemented back end for user itineraries index page, with option to delete itinerary. front end advanced, needs tweaks and nice details

user journey: user itineraries show page

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_checkbox.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/pages/_cities.scss
app/views/pages/home.html.erb
app/views/preferences/categories.html.erb
app/views/preferences/cities.html.erb
app/views/shared/_navbar.html.erb
config/environments/development.rb

final front end changes

---

app/views/itineraries/show.html.erb
app/views/preferences/categories.html.erb
app/views/preferences/cities.html.erb
app/views/preferences/duration.html.erb
app/views/stops/index.html.erb

margin and paddings

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_map.scss
app/controllers/itineraries_controller.rb
app/views/layouts/application.html.erb
app/views/stops/index.html.erb
db/seeds.rb

map frontend fixes

---

app/assets/stylesheets/components/_map.scss
app/controllers/itineraries_controller.rb

map popup done

---

app/assets/stylesheets/components/_button.scss
app/views/itineraries/index.html.erb

back btn to itinerary

---

app/views/preferences/cities.html.erb
config/environments/development.rb

Remove config

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/pages/_show.scss
app/views/preferences/cities.html.erb
db/seeds.rb

Added margin-bottom to cards container just before footer

Sight show page footer fix

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/pages/_show.scss
app/views/pages/home.html.erb
app/views/preferences/cities.html.erb
db/seeds.rb

For some reason, home button 'let's go' was not coded correctly. I noticed that this morning, because home button was not working. Now it's all good

Home button fix

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_checkbox.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/pages/_itineraries-index.scss
app/assets/stylesheets/pages/_show.scss
app/views/itineraries/index.html.erb
app/views/itineraries/show.html.erb
app/views/pages/home.html.erb
app/views/preferences/categories.html.erb
app/views/preferences/cities.html.erb
app/views/shared/_navbar.html.erb
app/views/stops/index.html.erb
db/seeds.rb

I just did the entire journey again fixing capitalization discrepancies, remodeled the itinerary index page cause I wasn't happy with it, touched up on a few buttons and cards.

Minor fe fixes
